---
#title: ConfWS 2025
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: single
    author_profile: false
    read_time: false
    share: false
    comments: false
    related: false
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: false
    comments: false
    share: true
    related: true
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: air
locale: en-US
title_separator: "-"
name: 27th International Workshop on Configuration (ConfWS'25)
description: Website of the 27th International Workshop on Configuration (ConfWS'25)
url: https://confws.github.io
baseurl: 
repository: confws/confws.github.io
teaser: 
logo: 'assets/confws/confws-2025-logo.png'
#masthead_title: ConfWS 2024
words_per_minute: 200
comments:
  provider: 
  disqus:
    shortname: 
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
  utterances:
    theme: 
    issue_term: 
staticman:
  allowedFields: 
  branch: 
  commitMessage: 
  filename: 
  format: 
  moderation: 
  path: 
  requiredFields: 
  transforms:
    email: 
  generatedFields:
    date:
      type: 
      options:
        format: 
  endpoint: 
reCaptcha:
  siteKey: 
  secret: 
atom_feed:
  path: 
search: true
search_full_content: true
search_provider: lunr
google_site_verification: "4e7d9bf007bbe84b"
bing_site_verification: 
yandex_site_verification: 
naver_site_verification:
  username: 
facebook:
  username: 
  app_id: 
  publisher: 
og_image: 'assets/confws/confws-2025-logo.png'
social:
  type: 
  name: 
  links: 
analytics:
  provider: false
  google:
    tracking_id: 
    anonymize_ip: false
author:
  # name: ''
  # avatar: assets/confws/uma-logo-transparent.png
  # bio: ''
  # home: 'https://www.uma.es/'
  # location:
  links:
#  - label: University of Málaga
#    icon: fas fa-fw fa-map-marker-alt
#    url: https://www.uma.es/  
  # - label: "Local organizer: CAOSD group"
  #   icon: fa fa-info-circle
  #   url: https://caosd.lcc.uma.es
  # - label: "ITIS Software"
  #   icon: fa fa-info-circle
  #   url: https://itis.uma.es/
#  - label: Follow ConfWS on Twitter
#    icon: fab fa-fw fa-twitter-square
#    url: https://twitter.com/ConfigurationWS
  - label: Follow ConfWS on LinkedIn
    icon: fab fa-fw fa-linkedin
    url: https://www.linkedin.com/groups/3718387/
  - label: "ConfWS: dblp computer science bibliography"
    icon: fa fa-book
    url: https://dblp.org/db/conf/confws/index.html
  #- label: Málaga Skyline logo by Miguel Sánchez Espinosa
  #  icon: fa fa-info-circle
  #  url: https://www.domestika.org/es/projects/291810-ilustracion-para-mapa-sonoro-malaga
  sponsors:
  - name: 'Sapienza'
    logo: assets/confws/sapienza.svg
    url: https://www.uniroma1.it/en
  - name: 'Padova'
    logo: assets/confws/padova.png
    url: https://www.unipd.it/en/
  - name: 'TUGraz'
    logo: assets/confws/tugraz.png
    url: https://www.tugraz.at/home
  - name: 'ASAI'
    logo: assets/confws/asai.png
    url: https://www.asai.ac.at/en/
  - name: 'MICS'
    logo: assets/confws/MICS_logo.png
    url: https://www.mics.tech
#  - name: 'Siemens'
#    logo: assets/confws/siemens-logo.png
#    url: https://www.siemens.com/global/en.html
  # projects: 
  # - name: 'Tasova Plus'
  #   logo: assets/confws/tasovaplus.png
  #   url: http://tasova.uma.es/
  # - name: DAEMON
  #   logo: assets/confws/daemon.png
  #   url: https://h2020daemon.eu/
  # - name: IRIS (PID2021-122812OB-I00)
  # - name: LEIA (UMA18-FEDERJA-157)
  # - name: Data-pl (PID2022-138486OB-I00)
  # - name: METAMORFOSIS (FEDER\_US-1381375)
footer:
  links:
#  - label: Twitter
#    icon: fab fa-fw fa-twitter-square
#    url: https://twitter.com/ConfigurationWS
  - label: LinkedIn
    icon: fab fa-fw fa-linkedin
    url: https://www.linkedin.com/groups/3718387/
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- NOTES
- tmp
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jemoji
- jekyll-include-cache
#- jekyll-google_search_console_verification_file
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jemoji
- jekyll-include-cache
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development